services:
  app:
    build: .
    container_name: stonk_train_container
    command: python3 ./src/main.py
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
